"""Pydantic schemas defining the agent's state and data structures."""

from datetime import datetime
from typing import Annotated, Optional
from operator import add

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class SearchResult(BaseModel):
    """A single search result from Tavily."""

    title: str
    url: str
    content: str
    score: float = Field(default=0.0, description="Relevance score from search engine")


class SubQuestion(BaseModel):
    """A sub-question generated by the planner."""

    question: str
    rationale: str = Field(description="Why this sub-question matters")
    results: list[SearchResult] = Field(default_factory=list)


class ResearchPlan(BaseModel):
    """Output of the planner node."""

    main_question: str
    sub_questions: list[SubQuestion]
    estimated_complexity: str = Field(
        description="One of: 'simple', 'moderate', 'complex'"
    )


class ReviewFeedback(BaseModel):
    """Output of the reviewer node."""

    is_sufficient: bool
    missing_aspects: list[str] = Field(default_factory=list)
    quality_score: int = Field(ge=1, le=10)
    comments: str


class ResearchReport(BaseModel):
    """Final report returned to the user."""

    query: str
    markdown: str
    sources: list[str]
    sub_questions: list[str]
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    quality_score: Optional[int] = None


class AgentState(TypedDict):
    """State shared across all LangGraph nodes.

    Using TypedDict (not Pydantic) because LangGraph requires it for
    proper state merging with reducers like `add` for list accumulation.
    """

    # Input
    query: str

    # Planner output
    plan: Optional[ResearchPlan]

    # Researcher output (accumulated)
    sub_questions: Annotated[list[SubQuestion], add]

    # Synthesizer output
    synthesis: Optional[str]

    # Writer output
    draft_report: Optional[str]

    # Reviewer output
    review: Optional[ReviewFeedback]
    iteration: int

    # Final
    final_report: Optional[ResearchReport]
